name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/node_modules
            ~/dist
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: content
          path: dist/
          if-no-files-found: error
  publish:
    name: "Publish"
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: site-deployment
      cancel-in-progress: false
    needs:
      - build
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Remove old content"
        run: git rm -r *
      - name: "Download generated content"
        uses: actions/download-artifact@v2
        with:
          name: content
      - name: "Commit changes"
        run: |
          set -euo pipefail
          git config user.name "ContainerSSH Build Agent"
          git config user.email 86986082+containersshbuilder@users.noreply.github.com
          git add .
          git commit -m "Automatic publishing"
          git push --set-upstream origin gh-pages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
